# This script has been adapted from https://gitlab.com/tkpapp/GitlabJuliaDemo.jl/blob/master/.gitlab-ci.yml
# image: julia:1.0                # image comes from Docker hub
# before_script:
#   # workaround for https://github.com/JuliaDocs/Documenter.jl/issues/686
#   - apt-get -qq update; apt-get -y install git; apt-get -y install make; apt-get -y install gcc
#   - julia --project=@. -e "import Pkg; Pkg.build()"

# default:
#   script:
#     - julia --project=@. -e "import Pkg; Pkg.test(; coverage = true)"

# pages:
#   stage: deploy
#   script:
#     - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
#     - julia --project=docs --color=yes docs/make.jl
#     - mv docs/build public # move to the directory picked up by Gitlab pages
#   artifacts:
#     paths:
#       - public
#   only:
#   - master

linux:
  image: julia:1.0                # image comes from Docker hub
  before_script:
    # workaround for https://github.com/JuliaDocs/Documenter.jl/issues/686
    - apt-get -qq update; apt-get -y install git; apt-get -y install make; apt-get -y install gcc
    - julia --project=@. -e "import Pkg; Pkg.build()"
  script:
    - julia --project=@. -e "import Pkg; Pkg.test(; coverage = true)"
  after_script:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit_local(process_folder())'
  tags:
    - linux

osx:
  before_script:
    # workaround for https://github.com/JuliaDocs/Documenter.jl/issues/686
    # - apt-get -qq update; apt-get -y install git; apt-get -y install make; apt-get -y install gcc
    - julia1.0 --project=@. -e "import Pkg; Pkg.build()"
  script:
    - julia1.0 --project=@. -e "import Pkg; Pkg.test(; coverage = true)"
  after_script:
    - julia1.0 -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit_local(process_folder())'
  tags:
    - osx
